### ISSUE TITLE
Update Home Design

### ISSUE THREAD

**Issue by Damianpad** [jesusdoza/pantryPal#49]
- Update Home Design
- Needs to be responsive
- Include Links to Sign up or Login
- Add About section with links to contributors and quick summary of what PantryPal does

**Comment by priddhesh** [comment]
Please assign me this task.

**Comment by jesusdoza** [comment]
@priddhesh 
> Please assign me this task.

Sorry that task was already being worked on. We might find something else if you still wanna work on something
